SRC_DIR=src
BUILD_DIR=build
BOOTLOADER_SRC=$(SRC_DIR)/bootloader.nasm
BOOTLOADER_BIN=$(BUILD_DIR)/bootloader.bin

all: $(BOOTLOADER_BIN)

$(BOOTLOADER_BIN): $(BOOTLOADER_SRC)
	nasm -f bin -o $(BOOTLOADER_BIN) $(BOOTLOADER_SRC)
